dist: xenial
language: go
go:
  - "1.11.x"

env:
  - GO111MODULE=on GOFLAGS=-mod=vendor

install:
  - make tools

jobs:
  include:
    - stage: test
      if: NOT tag IS present
      script:
        - make test
        - make
      on:
        branch: "master"
    - stage: deploy
      if: tag IS present
      script:
        - make test
        - make build-linux BUILDARGS="-o terraform-provider-ovc_$(git describe --tags --abbrev=0)-linux"
        - make build-darwin BUILDARGS="-o terraform-provider-ovc_$(git describe --tags --abbrev=0)-mac"
      deploy:
        provider: releases
        api_key: 
          secure: "xMiXl3h8VtbIV2kXDbzWVKXzNZIJqVLCqmXiNbsmGMH5mfYYs7GkWC4CqngCz24E+3GO4e7yvpxbpitcq801IgYKC/kLcMXdvnGGTGlRHYqHkonme+U+0A3WdMEmY+lHJfsRgHpMmpzcsCqBz6PKkhCfEa6T8+HVaphpayCMXH42OYrafQ0n/kZp0d90sHU/dNDYLqxycHXKc6HICnXhbLaWbItZkN03vykYmk5b3wFeOoWN6WX9r1JIwlR+H6DBPs+YbuJDR/mnzwTIlrXWWmJAvpafxqT/y2RBwE/VgiSME69o4tDqm455cQ6uY8AOnFVjZYHlcowg99hll1fm91fgnUYMKeKeWITGwqYb4hXHbq6xsLyCkRQXkf6O1KBn+Xwjp3hYq7rjj6fhuHKQPWh9hSOcxYR/BGyj60jlY4RkzPasHvSQdhSecrUOZXLIC66OMLkHrtxoZu0b+G7ePlsPv8HCDgWLjNcWDhzn7uFQFP8OYARVtYAbrsqd88+ytieomB5cZPBUE6fihPaTv3GwzC/RTzDINRa9JnCo78fyX14w+DEasVz102yU6ysDtytQZtWnhPkXF2nySdYcJCmrbUhaFfzhp7WZrEGaEDw8yX/NImC4zTt/F9nN0svdicOTQ8jPxYHAar0f+ZNXhpj7Ie/Nnj8Yuty9zObkoa0="
        file:
          - terraform-provider-ovc_$(git describe --tags --abbrev=0)-linux
          - terraform-provider-ovc_$(git describe --tags --abbrev=0)-mac
        skip_cleanup: true
        on:
          tags: true
